services:
  api:
    image: billetterie:${APP_VERSION}
    build:
      context: ../../
      dockerfile: Dockerfile
      target: production
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root
    restart: unless-stopped
    secrets:
      - mysql-root
    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          memory: '${MEMORY_LIMIT:-2G}'
          cpus: '${CPU_LIMIT:-1.0}'
        reservations:
          memory: '${MEMORY_RESERVATION:-512M}'
          cpus: '${CPU_RESERVATION:-0.5}'
    networks:
      - api-network

secrets:
  mysql-root:
    file: ../password.txt

networks:
  api-network:
    external: true