#chaque worker nginx peut gérer jusqu'à 1024 connexions simultanées
events { worker_connections 1024 ; }

http {
# définit des groupes de serveurs
# Voir : https://nginx.org/en/docs/http/ngx_http_upstream_module.html
# By default, requests are distributed between the servers using a weighted round-robin balancing method.
upstream api_servers {
# 'api' est le nom du service dans compose
server billetterie-green:3000 ;
}

server {
listen 80 ;

location / {
#passe requête au groupe du bloc 'upstream'
proxy_pass http://api_servers           ;
#transmet le nom de domaine fourni par le client
proxy_set_header Host $host             ;
#transmet un header avec l'IP du client
proxy_set_header X-Real-IP $remote_addr ;
}
}
}
